### ISSUE TITLE
Panel is to the right of the tabs

### ISSUE THREAD

**Issue by Ryah** [tovifun/VivalArc#13]
Not a huge issue, but it would be nice if I could somehow fix it. The panel shows to the right of the vertical tabs instead of to the left like the photos show. Not sure if I missed a step somewhere or if it's a code issue with a newer update.

![image](https://github.com/tovifun/VivalArc/assets/14987609/2fcfde50-117a-473d-8f82-2f9f6888664e)

**Comment by tovifun** [comment]
<img width="816" alt="image" src="https://github.com/tovifun/VivalArc/assets/11190955/41d75759-e934-4a87-99c0-8a4c476dbd89">
Hello, you can set the tab bar on the left in "Settings/Tabs."

**Comment by Ryah** [comment]
Yes, I did that. But the panel itself is to the right of the tabs. I want it to be on the left on the edge of the window, like this photo on your site.

![image](https://github.com/tovifun/VivalArc/assets/14987609/15059760-47c2-49df-8b3c-a8635f61fb11)

Is there any setting to do that?

**Comment by tovifun** [comment]
Understood, you can also set the panel position to the left side in "Settings/Panel."
<img width="463" alt="image" src="https://github.com/tovifun/VivalArc/assets/11190955/a8c958aa-67be-46de-a622-22d6a40fff56">

**Comment by HKayn** [comment]
@Ryah is VivalArc the only CSS mod you have installed in Vivaldi? This may be caused by another mod.

**Comment by tovifun** [comment]
@Ryah I just noticed in the first screenshot that the panel is on the right side of the tab bar.😂  I don't know how to achieve this effect; it's the first time I've seen it.

**Comment by HKayn** [comment]
This effect is something that my Vivaldi VH mod does. I think they have it installed alongside VivalArc.

**Comment by Ryah** [comment]
Yeah, I just now found out about the command chain flag `vvh-enable-panel-in-pillar` with the Vivaldi VH mod. After searching a bit I found the update for VivaldiVH that moved the panel away from the pillar. 

Fixed by adding the `vvh-enable-panel-in-pillar` command chain.

Apologies for the confusion lol. Thanks for the help!
