### ISSUE TITLE
win10安装主题提示:无法打开此文件  Vivaldi无法打开此文件夹内的文件，因为此文件夹含有系统文件

### ISSUE THREAD

**Issue by ChicoSir** [tovifun/VivalArc#14]
如图所示，我已经按照安装流程进行，Vivaldi为最新版本。

<img width="937" alt="Snipaste_2024-02-19_16-02-28" src="https://github.com/tovifun/VivalArc/assets/44128292/e16c848e-0594-404d-a109-ef87e3d6f339">
<img width="703" alt="Snipaste_2024-02-19_16-02-14" src="https://github.com/tovifun/VivalArc/assets/44128292/dc47e696-5ad6-4424-8dae-b947a7a58a6c">

**Comment by tovifun** [comment]
其他的主题可以吗，我晚点使用 Windows 测试一下

**Comment by ChicoSir** [comment]
> 其他的主题可以吗，我晚点使用 Windows 测试一下

其他一样，如上图提示

**Comment by tovifun** [comment]
我在windows上从零开始设置，发现是可以的，不太确定怎么才能复现，下方是在 Windows 从零开始的设置流程。
如果还是无法设置的话，你也可以尝试值下载最新的 [CSS 文件](https://github.com/tovifun/VivalArc/blob/main/vivalarc.css)（其他的主题文件之类的不下载），然后看能不能设置。
https://github.com/tovifun/VivalArc/assets/11190955/7f56d8ee-ae00-4b44-ab85-e4e4ab2a9d20
