### ISSUE TITLE
Close, Minimize and Maximize are very small

### ISSUE THREAD

**Issue by bashcrandicoot** [tovifun/VivalArc#15]
![540 Delirious Quillback](https://github.com/tovifun/VivalArc/assets/34585846/bade1a68-557b-4d76-8539-c16bf65ed1c1)

It's pretty hard to click and the only way I know how to fix it is using native ui, which is sloppy looking, hopefully this can be updated. :)

**Comment by tovifun** [comment]
For larger window button version, feel free to check out this release:
https://github.com/tovifun/VivalArc/releases/tag/v1.0.0-large-ui-controls

https://github.com/tovifun/VivalArc/assets/11190955/7ee973bb-bb8c-4764-a2b4-d88ec4dcbc69

https://github.com/tovifun/VivalArc/assets/11190955/894161f8-330f-4d77-9507-47301e551ea7
