### ISSUE TITLE
使用反饋與支持

### ISSUE THREAD

**Issue by bennyz327** [tovifun/VivalArc#16]
我也是一個期盼 arc 已久的 Windows/Linux  用戶，真的很高興有這樣一個項目能讓我實際體驗到 arc 的魅力

由於我近期沒有使用 Mac 的計畫，加上遲遲沒有收到 Windows 測試板的邀請（我很早就發送排隊表單了）
所以看到這個項目馬上就安裝上測試一下

目前我使用中的是 [EndeavourOS](https://endeavouros.com/) 作業系統中安裝的 vivaldi，初步體驗下來整體沒什麼大問題，我感到相當開心

唯一一個問題就是 **最大/小化和關閉的按鈕相當小**，如果調整成 native ui 又會太粗太佔空間
如同 #15 所提到的狀況一樣，希望作者有空能幫忙看看問題出在哪裡 (還是那是預期中的狀況，我不太確定)

再次感謝作者的貢獻以及這個專案帶給我的快樂！

**Comment by tovifun** [comment]
收到你的反馈真是太棒了！知道有人喜欢这个小项目我感到非常高兴。

目前收到了几个问题报告，有些用户说按钮太小了。但其实是因为边框很细，这样就有点限制了按钮的大小。这个问题有点棘手，因为如果边框太大，看起来又不够好看。

我下次更新的时候，可能会试试一种解决方案：稍微调大顶部边框的大小，这样窗口按钮就可以略微放大一些。

((😂我以为我回复过了，今天看issue才发现我之前是意念回复。。。))

**Comment by tovifun** [comment]
我添加了一个新的分支版本，把窗口按钮调大了一些：
https://github.com/tovifun/VivalArc/releases/tag/v1.0.0-large-ui-controls

https://github.com/tovifun/VivalArc/assets/11190955/7ee973bb-bb8c-4764-a2b4-d88ec4dcbc69

https://github.com/tovifun/VivalArc/assets/11190955/894161f8-330f-4d77-9507-47301e551ea7
