### ISSUE TITLE
Traffic Icons overlapping with UI

### ISSUE THREAD

**Issue by Blendertom** [tovifun/VivalArc#17]
The traffic light buttons overlap with the icon text of Workspaces.

![CleanShot 2024-04-27 at 15 17 56@2x](https://github.com/tovifun/VivalArc/assets/3437365/a947f911-2d0a-4809-a99e-dbca4bba8c98)

**Comment by tovifun** [comment]
In the recent updates of Vivaldi 6.7, the traffic icon of macOS cannot be customized 🥲. I will soon release an update of VivalArc with a compromise solution.
![CleanShot 2024-04-27 at 20 12 07@2x](https://github.com/tovifun/VivalArc/assets/11190955/7343117c-6113-4e79-9ec7-164f932c3f77)

**Comment by Blendertom** [comment]
That doesn't look like a compromise at all!

Thank you for the quick response. I thought I was doing something wrong.

**Comment by zxux** [comment]
+1, same issue, when will update released

**Comment by tovifun** [comment]
> +1, same issue, when will update released

It's gonna be this weekend 😂

**Comment by tovifun** [comment]
Hi @Blendertom @zxux, 
Just [released a version ](https://github.com/tovifun/VivalArc/releases/tag/v1.0.2)that fixes this issue.
