### ISSUE TITLE
traffic icon in page popup window looks a little weird

### ISSUE THREAD

**Issue by zxux** [tovifun/VivalArc#18]
<img width="800" alt="image" src="https://github.com/tovifun/VivalArc/assets/59725850/904faa3e-32b2-4220-88de-9486ccba0136">

maybe a Google auth can invoke a popup window

**Comment by tovifun** [comment]
The issue should have been resolved. -> https://github.com/tovifun/VivalArc/releases/tag/v.1.0.4.1
![vivalarc_issue_18](https://github.com/user-attachments/assets/17b4434d-9349-4e65-940d-10c0f71186cb)

**Comment by TYZRPVX** [comment]
```
/* Popup: add margin to URL */
#browser:is(.popup) .mainbar {
  padding-top: 24px;
}
```

when hiding titlebar, this code works
