### ISSUE TITLE
书签和历史记录点击不可用

### ISSUE THREAD

**Issue by calliu** [tovifun/VivalArc#2]
非常感谢tovifun的付出。我在使用中发现两个小问题：
1. 关闭/最小化/最大化 按钮随标题栏一起消失了，使用时有点不太方便，
2. 侧边栏（panel）的书签、历史记录的点击和触控板滑动似乎失效了。

**Comment by tovifun** [comment]
收到，这两天也发现了这个问题。这个问题是Vivaldi版本更新后产生的。我找个时间👀能不能解决下。

目前你可以暂时通过将面板放置在右边来使用。

**Comment by tovifun** [comment]
关于最大化，因为我习惯是双击侧边栏来最大化，所以隐藏了左上角窗口的按钮。

如果需要关闭或最小化(非常低频的操作)，就command + t 打开快捷命令，输入关闭或者最小化。
