### ISSUE TITLE
Win 的新版本 Vivaldi 开启左侧标签栏后，工作区下的分割线与第一个标签页有重合

### ISSUE THREAD

**Issue by n1nelink** [tovifun/VivalArc#20]
## System Env

- 操作系统：Windows 11 家庭中文版
- 浏览器版本：Vivaldi 6.8.3381.46

## Problem

在新版本的 Vivaldi 中，工作区下添加了一条下划线

使用仓库中的 CSS 配置，开启左侧标签栏后，在开启 “显示工作区” 选项后，工作区下的第一个标签页会与工作区下的分割线重合，如下图所示

![image](https://github.com/tovifun/VivalArc/assets/164283558/46a0e883-c06a-48c3-90e3-289237b64c2c)

**Comment by n1nelink** [comment]
然后我是这样处理这个问题的，我不是搞前端的，所以不知道这样修改合不合适

但是在我目前的使用情况来看，是可以解决问题的：

在 `vivalarc.css` 文件中追加下面的 css 代码：

```css
/* Workspace separator hr*/
.separator.separator-wsbutton hr {
    margin-block: -8px;
}
```

---

修改后的效果图：

![image](https://github.com/tovifun/VivalArc/assets/164283558/d0bc673f-8d3c-41c9-ba7f-4eac390bcedb)

希望对其他有类似问题的朋友有帮助

**Comment by n1nelink** [comment]
> 然后我是这样处理这个问题的，我不是搞前端的，所以不知道这样修改合不合适
> 
> 但是在我目前的使用情况来看，是可以解决问题的：
> 
> 在 `vivalarc.css` 文件中追加下面的 css 代码：
> 
> ```css
> /* Workspace separator hr*/
> .separator.separator-wsbutton hr {
>     margin-block: -8px;
> }
> ```
> 
> 修改后的效果图：
> 
> ![image](https://private-user-images.githubusercontent.com/164283558/344139599-d0bc673f-8d3c-41c9-ba7f-4eac390bcedb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzQ1NzMsIm5iZiI6MTcxOTU3NDI3MywicGF0aCI6Ii8xNjQyODM1NTgvMzQ0MTM5NTk5LWQwYmM2NzNmLThkM2MtNDFjOS1iYTdmLTRlYWMzOTBiY2VkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxMTMxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTNlOGI2ZDBiNThhNjM3MTc0NTE5MTJjNWMzNDU2YmVlOWQxZTg4MDlmYjI2MmQzMzQxMDZiNGZkMTQyODNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yb_Ra1usIpxVWT23Uvm3FGXBd63-3joCL5bvLLzYH88)
> 
> 希望对其他有类似问题的朋友有帮助

🤔 这个方法好像在固定标签页的时候会上下两条分割线边距不协调，这样改好像会好点：

```css
#tabs-container.left {
    margin-top: 14px;
}
```

![image](https://github.com/tovifun/VivalArc/assets/164283558/c3ad9ed9-6d1b-4aee-8c82-c161253371e1)

**Comment by tovifun** [comment]
我今天也刚好处理了这个，我明天上午发布一下更新哈

**Comment by tovifun** [comment]
https://github.com/tovifun/VivalArc/releases/tag/v1.0.3
@NextEcho 刚刚发布了一个修复了这个问题的版本
