### ISSUE TITLE
Really small but i have this annoying bot around the task bar kind stupid but how do i fix this? it keeps catching my eye

### ISSUE THREAD

**Issue by ComplexSlayers2** [tovifun/VivalArc#24]
![Screenshot_20240807_032512](https://github.com/user-attachments/assets/9b2b80b7-170f-49fe-b005-8beb718c5f84)

**Comment by tovifun** [comment]
Hi, could you clarify what you mean by the "annoying bot around the taskbar"? 
Are you referring to the Vivaldi logo, or something else?

**Comment by vComplex1** [comment]
> Hi, could you clarify what you mean by the "annoying bot around the taskbar"? Are you referring to the Vivaldi logo, or something else?

hey sorry for the typo i meant grey box ill send another picture that will be clearer

**Comment by vComplex1** [comment]
![image](https://github.com/user-attachments/assets/d96cd36b-be6b-475f-8237-45e18d229ee5)
see the lighter box around the tabs, thats what i mean, how can i fix it?

**Comment by tovifun** [comment]
Oh, I see, you’re using Vivaldi Snapshot 6.9? The recently updated Vivaldi 6.9 has this issue. I’ll be releasing a new version of VivalArc today to address the problem with the Tabbar background.

**Comment by vComplex1** [comment]
> Oh, I see, you’re using Vivaldi Snapshot 6.9? The recently updated Vivaldi 6.9 has this issue. I’ll be releasing a new version of VivalArc today to address the problem with the Tabbar background.

yes i was using the snapshot, thanks for telling me

**Comment by tovifun** [comment]
The issue should have been resolved (Just update to the latest CSS file.): 
https://github.com/tovifun/VivalArc/releases/tag/v.1.0.4.1
