### ISSUE TITLE
Top left corner 3 dots and center title

### ISSUE THREAD

**Issue by everpromos** [tovifun/VivalArc#26]
Hello,

Can anyone help? thanks in advance!
- Top left corner - the 3 dots seems overlay, maybe its about the interface zoom settings, but i want to keep 110%.
- Top center i want to show the page title, similar to the demo image.

![Screen Shot 2024-08-13 at 07 27 54](https://github.com/user-attachments/assets/b428db21-0ac2-49b7-9bb4-2663b5857def)
 
![theme_arclight](https://github.com/user-attachments/assets/fae1eccb-dc68-4cff-a5db-cde53665ae9a)

**Comment by tovifun** [comment]
Hey, I recorded a video showing how to set up the top title bar with a page title. You can check it out at this link:
https://github.com/tovifun/VivalArc/blob/main/docs/vivalarc-variants.md
