### ISSUE TITLE
在v6.9中，无法显示状态栏

### ISSUE THREAD

**Issue by IamMiao** [tovifun/VivalArc#28]
尝试了VivalArc的default、large-ui和compact-ui，无论状态栏设置为显示还是浮动，都无法出现，取消VivalArc的CSS应用，状态栏就会出现

我也非常喜欢vivaldi的页面平铺功能，不知道能否在地址栏或者其他地方单独显示页面平铺的功能按钮，这样就不需要为了一个功能按钮而显示一行状态栏了

非常感谢作者提供如此精美的CSS样式文件！

**Comment by tovifun** [comment]
不好意思呀，这个状态栏我在 CSS 里给隐藏了，我可以下次更新的时候，修改一下。
不过，如果是想用平铺功能的话，我觉得用鼠标右键、或者快捷命令也挺方便的，我在下方视频里给你演示一下：

https://github.com/user-attachments/assets/b2daca9a-e673-496e-a83a-b7795c135945

**Comment by everpromos** [comment]
这样是不是也是一种替代方案呢 
![Xnip2024-09-02_19-15-22](https://github.com/user-attachments/assets/ddfc960b-1d2f-47ec-8079-8ad8aabc6ca9)

**Comment by tovifun** [comment]
咦，我之前不知道还能把状态栏的控件给放到地址栏上

**Comment by everpromos** [comment]
> 咦，我之前不知道还能把状态栏的控件给放到地址栏上

是的 有时候需要用到地址栏 shift+command+D

**Comment by IamMiao** [comment]
这是如何实现的?工具栏编辑器中的地址栏中并没有页面平铺按钮,反而在状态栏中有

**Comment by tovifun** [comment]
谢谢你们，才发现这个设置：
@IamMiao @everpromos 

https://github.com/user-attachments/assets/5693ddae-f36a-4c8e-a6b5-4b307abb29ec

**Comment by tovifun** [comment]
在新发布的 VivalArc中，Footer 现在默认可见，但仍然可以在设置中将其隐藏 🌹
https://github.com/tovifun/VivalArc/releases/tag/v.1.1.0
