### ISSUE TITLE
最大化窗口后浏览器崩溃

### ISSUE THREAD

**Issue by m1509001** [tovifun/VivalArc#3]
安装的你最新的主题，
浏览器的版本是：5.8.2970.3 (官方版) (arm64) 

操作系统 | macOS 版本13.3（版号22E252）
-- | --

我点击最大化就会崩溃，我使用官方的主题不存在这个问题，使用你这个上个版本主题也没有出现崩溃

**Comment by tovifun** [comment]
抱歉，我检查下

**Comment by tovifun** [comment]
我用你这个版本的 vivaldi 和 13.2 的 macos，没有复现这个全屏崩溃，我再看看🤣

**Comment by m1509001** [comment]
> 

我删除了浏览各种历史记录，重新尝试，发现不再崩溃了，可能是浏览器本身的问题
不过我最开始确实只是安装了你这个主题的账户窗口最大化会崩溃，别的账号窗口不会崩溃，
不知道哪里的问题，谢谢
