### ISSUE TITLE
如何移動彈出的小視窗

### ISSUE THREAD

**Issue by yangbentw** [tovifun/VivalArc#30]
如圖
![image](https://github.com/user-attachments/assets/d5e29891-b673-4b66-93fd-3e07548b1a99)

如果彈出這樣的視窗，沒有地方可以拖曳

我是否缺少了哪些設定呢

**Comment by Zettry** [comment]
可以考虑修改 `vivalarc.css`，在文件中搜索
```
.color-behind-tabs-off.address-top#browser:not(.tabs-top):not(.tabs-bottom) .mainbar
```
然后添加 `padding-top` 来增加窗口顶部间隔。

有一定间隔后鼠标就能够拖动窗口了，间隔的大小可以看自己喜欢设置合适的大小。

![image](https://github.com/user-attachments/assets/c3e31f7f-03aa-4358-bc33-fb7a90b65317)

**Comment by yangbentw** [comment]
還是不行
我故意改成70px，但無法移動
![image](https://github.com/user-attachments/assets/ab27ea90-0d9d-4213-a25f-bac71c79ddd7)

如果不使用vivalarc.css，則可移動
![image](https://github.com/user-attachments/assets/5e1cea7f-f104-4457-a1c0-894d8b75996b)

**Comment by Zettry** [comment]
@yangbentw @tovifun 仔细看了下你的截图，应该是滴答清单的插件弹出的窗口。Inspect 查看是 mainbar 拖动属性问题。

还是修改 `vivalarc.css` 相同的地方，增加 `-webkit-app-region: drag;`，就可以解决这个问题了。

![image](https://github.com/user-attachments/assets/3dc813de-cc54-4b3d-a488-572a210fdeab)

**Comment by yangbentw** [comment]
成功了，非常感謝

**Comment by tovifun** [comment]
这个样式加入了最新发布的 VivalArc 🌷
https://github.com/tovifun/VivalArc/releases/tag/v.1.1.0
