### ISSUE TITLE
vivalarc-autotab 展開是透明的

### ISSUE THREAD

**Issue by yangbentw** [tovifun/VivalArc#32]
tab hover展開是透明的

看了論壇教學後，嘗試找了一下
好像是var(--colorImageLeftBg)沒定義

```
.inner > .tabbar-wrapper > .tabbar-wrapper:hover{
    position: absolute;
    background:var(--colorImageLeftBg);
}
```

是我少做了什麼步驟嗎

**Comment by yangbentw** [comment]
好像跟主題有關，我試了幾個

- 會變透明
Dark
Subtle
Issuna
Arc Dark Pure

- 不會透明
Vivaldi
Paint
Soft Pink
Beach
Human
Purple Rain
Private
Sunset Into the mountain
Purple Magic
Arc Dark Clementpoiret
VivalArc Reflect DarkPurple

**Comment by tovifun** [comment]
刚发了一个修复版本。
前面忘了还有些主题没有设置背景图片，现在给hover状态的标签栏下，加了一个如果没有背景图的时候，使用背景颜色作为备选：
![image](https://github.com/user-attachments/assets/6b0e89af-ad7d-4961-9e1b-8c1b8776a70b)
