### ISSUE TITLE
autotab模式下侧边栏展开时颜色不对

### ISSUE THREAD

**Issue by Daedemons** [tovifun/VivalArc#33]
使用1.1.1版本的autotab.css时，选择arcLight主题，若侧边栏收起时，正常显示粉蓝渐变的主题色。但是鼠标挪到侧边栏，侧边栏展开时，地址栏与侧边栏有明确的颜色分层
![image](https://github.com/user-attachments/assets/7f412349-eeef-40b2-96b6-321ef6b448ba)

**Comment by tovifun** [comment]
**可以参考这个 Issue #21  回复：**

- 如果要颜色一致的话，目前可以通过获取浏览器背景图作为hover的背景，但是这个背景图，每个人的地址都是不一样的，所以我在样式里使用背景颜色作为替代；
- 目前来说我觉得背景颜色已经效果可以，正常来说看不到背景颜色，悬停的时候才会这个颜色分层；
- 如果你想要效果好一点的话，可以找一下找到当前 Vivaldi 的背景图地址；

**替换背景方式：**
1. 打开地址：vivaldi:inspect/#apps
2. 找到背景图
3. 在下方图里的位置粘贴使用背景
4. 重启Vivaldi

  **Vivaldi 背景图**
  <img width="1020" alt="image" src="https://github.com/user-attachments/assets/0be6ea3d-84fe-44e8-9a80-8df3730eed0d">
  
  **在 `.tabbar-wrapper:hover` 使用背景图**
  <img width="736" alt="image" src="https://github.com/user-attachments/assets/ad5dd21e-1b4a-420a-b8ec-8b1e26dce915">
  
**视频演示**
  https://github.com/user-attachments/assets/ab1b0f8c-5f0d-4e4b-b23e-5193c61c7a29
