### ISSUE TITLE
Ultra Narrow Tab Bar 

### ISSUE THREAD

**Issue by wilberfan** [tovifun/VivalArc#34]
I haven't been able to find any discussion of how to make the tab bar narrow, as shown on your home page.  A keyboard shortcut would be ideal...  Apologies if I missed something obvious.  

<img width="623" alt="ultra narrow" src="https://github.com/user-attachments/assets/0e6eda7a-714e-4d96-95dc-4ca2f44f3b26">

**Comment by tovifun** [comment]
There are two options:

1. Drag the sidebar directly based on the default style.

https://github.com/user-attachments/assets/25e03ddf-98c4-4718-850f-5168e1d42fc9

--- 

2. Use the latest VivalArc variant, vivalarc-autotab, which automatically hides the tab bar and only expands it on hover (see #21 for reference).

https://github.com/user-attachments/assets/c5606d7e-cb1b-4585-83bb-3b5532a04f72

_**For easier tab bar hiding, you can set a shortcut to toggle its visibility. I set the shortcut to `Command/Ctrl + S.`**_
