### ISSUE TITLE
win端ui问题

### ISSUE THREAD

**Issue by Sunny-XXV** [tovifun/VivalArc#4]
win11 22H2，最新版vivaldi

按照教程配置，出现问题：vivaldi顶端的那一条（菜单栏？）无法正常显示，将鼠标悬浮至对应位置会出现相应文字；右上角最小化、窗口化和关闭按钮大小与不正常，如图：
![image](https://github.com/tovifun/VivalArc/assets/70095587/e695cffa-7fb7-418d-ac6e-a84618fdd794)

尝试2023/03/27发布的版本无此问题。
![image](https://github.com/tovifun/VivalArc/assets/70095587/b9ff5485-45e6-4a07-887a-5e122dd15c79)

**Comment by tovifun** [comment]
收到，我过几天更新一下CSS

**Comment by tovifun** [comment]
Hello，这个问题找到啦，是因为我之前没发现Windows上是有横向菜单栏的功能的，于是没适配。可以关掉这个功能（view>Horizontal Main Menu）。
