### ISSUE TITLE
顶部可拖动窗口的地方有点小，拖起来比较困难😭

### ISSUE THREAD

**Issue by Alex-Zhangzhipeng** [tovifun/VivalArc#8]
问题如题，使用触摸板拖动页面比较困难，而arc的拖动包含了页面内最上方的一部分内容，拖动相对简单。作者目前完成的部分已经很不错了。

**Comment by tovifun** [comment]
谢谢！我目前在准备一个新功能，可以通过调整几个数值来供大家自定义一些UI样式，比如下面这个可以调整边框粗细：
![image](https://github.com/tovifun/VivalArc/assets/11190955/f4f69bc3-e91f-479c-baf0-be6263d81c9e)

我还在想一些别的额外的自定义的东西，可能包括在 tabbar 加入拖拽。

**Comment by Alex-Zhangzhipeng** [comment]
好的好的，那就保持期待

**Comment by tovifun** [comment]
Hello，我周末更新了一下，这个目前应该可以解决啦，不过要额外配置一点点东西，你可以看看这个详细的配置方式： https://github.com/tovifun/VivalArc/blob/main/docs/changelog-cn.md
