### ISSUE TITLE
UI not working ?

### ISSUE THREAD

**Issue by volrod64** [tovifun/VivalArc#9]
Hello ! 
First of all, thanks for this project, it look amazing !
My issue is that I'm on the latest Vivaldi version 6.4.3160.47 and I can't make the UI work.
In Custom UI modification I put C:\Users\me\Downloads\VivalArc-main\ (also tried with C:\Users\me\Downloads\VivalArc-main\CSS) but both aren't working, my UI still look the same after restarting the browser.
![image](https://github.com/tovifun/VivalArc/assets/94232342/452c9c0b-8597-4655-b746-a958928e3e63)
May I ask for a little help ? 
Thanks :)

**Comment by tovifun** [comment]
> Hello ! First of all, thanks for this project, it look amazing ! My issue is that I'm on the latest Vivaldi version 6.4.3160.47 and I can't make the UI work. In Custom UI modification I put C:\Users\me\Downloads\VivalArc-main\ (also tried with C:\Users\me\Downloads\VivalArc-main\CSS) but both aren't working, my UI still look the same after restarting the browser. ![image](https://private-user-images.githubusercontent.com/94232342/290191342-452c9c0b-8597-4655-b746-a958928e3e63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzU5NDcsIm5iZiI6MTcwMjUzNTY0NywicGF0aCI6Ii85NDIzMjM0Mi8yOTAxOTEzNDItNDUyYzljMGItODU5Ny00NjU1LWI3NDYtYTk1ODkyOGUzZTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA2MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YjlmMDMzMzQ5MjNjNzAwNzE0MTkwNjNkMWMxYTk1OGNiMDY1ZWNhODViZGE5ZDgyYWUyZmEyYzllZjNkOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sCyLH9L9TDwFFw-MAzERVZaDdbZWs879OdEA--qzz6w) May I ask for a little help ? Thanks :)

Hello, thank you very much for your interest and usage. There might be a slight issue with the file path. Have you considered placing the file in a different location and then selecting it again? (Make sure to choose the root directory of the VivalArc-main folder.)

**Comment by volrod64** [comment]
Hello
I'm using the path C:\Users\me\Downloads\VivalArc-main or C:\Users\me\Documents\VivalArc-main and thie issue is still the same :/
![image](https://github.com/tovifun/VivalArc/assets/94232342/19cbe0ab-07b6-4364-943d-c87ef74f5cfb)

**Comment by tovifun** [comment]
Hello, I looked at the screenshots you provided above, and it seems the UI is just right. Could you share a screenshot of your browser as well?

**Comment by volrod64** [comment]
![image](https://github.com/tovifun/VivalArc/assets/94232342/327dd9c5-c351-4c4d-88b3-1e72b61f3caa)
I can't even picture it, but everything is super small
